// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChddiTZn_RsMeTVe2HYILOP1NhNuOjDik',
    appId: '1:235202937843:web:b3884381a70db7009b4886',
    messagingSenderId: '235202937843',
    projectId: 'neolivra',
    authDomain: 'neolivra.firebaseapp.com',
    storageBucket: 'neolivra.firebasestorage.app',
    measurementId: 'G-FDZWC99WNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdd3nNZ2u3nv3NDujB4edm0BgIKUJYYAw',
    appId: '1:235202937843:android:fa5e91d13699fe979b4886',
    messagingSenderId: '235202937843',
    projectId: 'neolivra',
    storageBucket: 'neolivra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZCP0R35_8G3Viv5r0_lJ86t0-8WpCzxs',
    appId: '1:235202937843:ios:440b00a77afff6559b4886',
    messagingSenderId: '235202937843',
    projectId: 'neolivra',
    storageBucket: 'neolivra.firebasestorage.app',
    iosBundleId: 'com.example.neolivra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZCP0R35_8G3Viv5r0_lJ86t0-8WpCzxs',
    appId: '1:235202937843:ios:440b00a77afff6559b4886',
    messagingSenderId: '235202937843',
    projectId: 'neolivra',
    storageBucket: 'neolivra.firebasestorage.app',
    iosBundleId: 'com.example.neolivra',
  );

}